In [ ]:
import pandas as pd
 
# Ruta al archivo Parquet
archivo_parquet = '../output/caracteristicas.parquet'
 
# Leer el archivo Parquet
df_caracteristicas = pd.read_parquet(archivo_parquet)
 
# Mostrar las primeras filas del DataFrame
print(df.head())

   ID_Equipo    Tipo_Equipo Fabricante Modelo  Potencia_kW  \
0          1          Motor  Schneider   X100         1009
1          2          Motor        ABB   Z300         1220
2          3          Motor         GE   Y200         3733
3          4  Transformador    Siemens   X100          662
4          5      Compresor        ABB   Y200          982

   Horas_Recomendadas_Revision
0                         9656
1                         2165
2                         6674
3                         1480
4                         4282

In [2]:
import pandas as pd
def carga_parquet(ruta):

# Leer el archivo Parquet
    df = pd.read_parquet(ruta)
    return(df)

In [3]:
df_caracteristicas=carga_parquet('../output/caracteristicas.parquet')
df_caracteristicas

,ID_Equipo,Tipo_Equipo,Fabricante,Modelo,Potencia_kW,Horas_Recomendadas_Revision
0,1,Motor,Schneider,X100,1009,9656
1,2,Motor,ABB,Z300,1220,2165
2,3,Motor,GE,Y200,3733,6674
3,4,Transformador,Siemens,X100,662,1480
4,5,Compresor,ABB,Y200,982,4282
...,...,...,...,...,...,...
495,496,Motor,Siemens,X100,3617,5594
496,497,Generador,Schneider,Y200,548,8614
497,498,Motor,Schneider,M400,2602,5874
498,499,Motor,ABB,M400,877,6907
499,500,Transformador,GE,X100,2039,5082

In [4]:
df_ordenes=carga_parquet('../output/ordenes.parquet')
df_ordenes

,ID_Orden,ID_Equipo,Fecha,Tipo_Mantenimiento,Costo_Mantenimiento,Duracion_Horas,Ubicacion
0,1,465,2020-01-01 00:00:00,Correctivo,1405.20,47,Planta Norte
1,2,418,2020-01-01 01:00:00,Correctivo,5922.92,38,Planta Norte
2,3,228,2020-01-01 02:00:00,Correctivo,7119.05,34,Planta Oeste
3,4,300,2020-01-01 03:00:00,Correctivo,3488.33,38,Planta Oeste
4,5,325,2020-01-01 04:00:00,Correctivo,5611.37,15,Planta Este
...,...,...,...,...,...,...,...
9995,9996,42,2021-02-20 11:00:00,Preventivo,2790.17,25,Planta Este
9996,9997,66,2021-02-20 12:00:00,Correctivo,3802.44,3,Planta Sur
9997,9998,289,2021-02-20 13:00:00,Correctivo,4525.96,23,Planta Este
9998,9999,209,2021-02-20 14:00:00,Preventivo,1871.95,30,Planta Oeste
9999,10000,393,2021-02-20 15:00:00,Preventivo,8786.55,7,Planta Oeste

In [5]:
df_registros=carga_parquet('../output/registros.parquet')
df_registros

,ID_Registro,ID_Equipo,Fecha,Temperatura_C,Vibracion_mm_s,Horas_Operativas
0,1,147,2020-01-01 00:00:00,124.61,3.49,61609.0
1,2,111,2020-01-01 01:00:00,58.12,3.62,49474.0
2,3,475,2020-01-01 02:00:00,124.86,3.36,59760.0
3,4,337,2020-01-01 03:00:00,110.45,1.56,27752.0
4,5,212,2020-01-01 04:00:00,70.53,4.89,33066.0
...,...,...,...,...,...,...
8995,8996,201,2021-01-09 19:00:00,112.75,1.07,56253.0
8996,8997,475,2021-01-09 20:00:00,50.67,3.28,27276.0
8997,8998,96,2021-01-09 21:00:00,133.86,0.74,75860.0
8998,8999,449,2021-01-09 22:00:00,84.72,1.77,11775.0
8999,9000,455,2021-01-09 23:00:00,127.40,1.34,7354.0

In [7]:
df_tabla_final=carga_parquet('../output/tabla_final.parquet')
df_tabla_final.columns

Index(['ID_Equipo', 'Total_Ordenes', 'Ordenes_Correctivo',
       'Ordenes_Preventivo', 'MEDIA_DIAS_ENTRE_MTOS',
       'MEDIA_DIAS_ENTRE_MTO_PREV', 'DIAS_ENTRE_FALL_CONSEC',
       'Vida_util_estimada', 'MEDIA_TEMP', 'MEDIA_VIBR',
       'MEDIA_HORAS_OPERATIVAS', 'COSTE_MTO_CORR_MEDIO_POR_ORDEN',
       'DURACION_HORAS_CORR_MEDIO_POR_ORDEN', 'COSTE_MTO_CORR_TOTAL',
       'DURACION_HORAS_CORR_TOTAL', 'COSTE_MTO_PREV_MEDIO_POR_ORDEN',
       'DURACION_HORAS_PREV_MEDIO_POR_ORDEN', 'COSTE_MTO_PREV_TOTAL',
       'DURACION_HORAS_PREV_TOTAL', 'COSTE_MTO_MEDIO_POR_ORDEN',
       'DURACION_HORAS_MEDIO_POR_ORDEN', 'COSTE_MTO_TOTAL',
       'DURACION_HORAS_TOTAL', 'Tipo_Equipo', 'Fabricante', 'Modelo',
       'Potencia_kW', 'Horas_Recomendadas_Revision'],
      dtype='object')

In [10]:
df_otras_caract=df_tabla_final[['DIAS_ENTRE_FALL_CONSEC', 'ID_Equipo','DIAS_ENTRE_FALL_CONSEC','MEDIA_TEMP', 'MEDIA_VIBR',
       'MEDIA_HORAS_OPERATIVAS', 'Ordenes_Correctivo', 'DURACION_HORAS_CORR_MEDIO_POR_ORDEN', 'DURACION_HORAS_CORR_TOTAL','COSTE_MTO_CORR_TOTAL', 'COSTE_MTO_CORR_MEDIO_POR_ORDEN']]
df_otras_caract

,DIAS_ENTRE_FALL_CONSEC,ID_Equipo,DIAS_ENTRE_FALL_CONSEC,MEDIA_TEMP,MEDIA_VIBR,MEDIA_HORAS_OPERATIVAS,Ordenes_Correctivo,DURACION_HORAS_CORR_MEDIO_POR_ORDEN,DURACION_HORAS_CORR_TOTAL,COSTE_MTO_CORR_TOTAL,COSTE_MTO_CORR_MEDIO_POR_ORDEN
0,39.111111,1,39.111111,106.908125,2.346250,48090.312500,10,15.400000,154,52848.73,5284.873000
1,55.333333,2,55.333333,95.310000,2.400769,64532.615385,7,16.857143,118,22879.74,3268.534286
2,41.666667,3,41.666667,93.922778,3.232222,42117.111111,10,12.800000,128,29236.02,2923.602000
3,34.454545,4,34.454545,90.881500,2.278500,56715.350000,12,23.500000,282,82749.39,6895.782500
4,38.000000,5,38.000000,107.714643,2.693214,54120.142857,10,24.400000,244,47873.65,4787.365000
...,...,...,...,...,...,...,...,...,...,...,...
494,29.909091,495,29.909091,105.388947,2.308947,54310.421053,12,21.583333,259,70900.69,5908.390833
495,40.000000,496,40.000000,91.598750,2.845000,46477.541667,10,29.300000,293,58508.27,5850.827000
496,35.700000,497,35.700000,114.621053,2.642105,53482.947368,11,21.272727,234,54972.12,4997.465455
497,33.888889,498,33.888889,100.603333,2.572667,56706.866667,10,24.600000,246,53954.26,5395.426000
498,88.333333,499,88.333333,95.410000,2.761000,61050.000000,4,33.250000,133,20625.56,5156.390000

UNIMOS LAS TABLAS DE CARACTERISTICAS, OTRAS CARACTERISTICAS Y ORDENES

In [11]:
tabla_aux = pd.merge(df_caracteristicas,df_otras_caract, on="ID_Equipo")
tabla_aux

,ID_Equipo,Tipo_Equipo,Fabricante,Modelo,Potencia_kW,Horas_Recomendadas_Revision,DIAS_ENTRE_FALL_CONSEC,DIAS_ENTRE_FALL_CONSEC,MEDIA_TEMP,MEDIA_VIBR,MEDIA_HORAS_OPERATIVAS,Ordenes_Correctivo,DURACION_HORAS_CORR_MEDIO_POR_ORDEN,DURACION_HORAS_CORR_TOTAL,COSTE_MTO_CORR_TOTAL,COSTE_MTO_CORR_MEDIO_POR_ORDEN
0,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.346250,48090.312500,10,15.400000,154,52848.73,5284.873000
1,2,Motor,ABB,Z300,1220,2165,55.333333,55.333333,95.310000,2.400769,64532.615385,7,16.857143,118,22879.74,3268.534286
2,3,Motor,GE,Y200,3733,6674,41.666667,41.666667,93.922778,3.232222,42117.111111,10,12.800000,128,29236.02,2923.602000
3,4,Transformador,Siemens,X100,662,1480,34.454545,34.454545,90.881500,2.278500,56715.350000,12,23.500000,282,82749.39,6895.782500
4,5,Compresor,ABB,Y200,982,4282,38.000000,38.000000,107.714643,2.693214,54120.142857,10,24.400000,244,47873.65,4787.365000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,495,Compresor,Schneider,Y200,4383,6188,29.909091,29.909091,105.388947,2.308947,54310.421053,12,21.583333,259,70900.69,5908.390833
495,496,Motor,Siemens,X100,3617,5594,40.000000,40.000000,91.598750,2.845000,46477.541667,10,29.300000,293,58508.27,5850.827000
496,497,Generador,Schneider,Y200,548,8614,35.700000,35.700000,114.621053,2.642105,53482.947368,11,21.272727,234,54972.12,4997.465455
497,498,Motor,Schneider,M400,2602,5874,33.888889,33.888889,100.603333,2.572667,56706.866667,10,24.600000,246,53954.26,5395.426000
498,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.761000,61050.000000,4,33.250000,133,20625.56,5156.390000

In [13]:
tabla_modelo= pd.merge(tabla_aux,df_ordenes, on="ID_Equipo")
tabla_modelo

,ID_Equipo,Tipo_Equipo,Fabricante,Modelo,Potencia_kW,Horas_Recomendadas_Revision,DIAS_ENTRE_FALL_CONSEC,DIAS_ENTRE_FALL_CONSEC,MEDIA_TEMP,MEDIA_VIBR,...,DURACION_HORAS_CORR_MEDIO_POR_ORDEN,DURACION_HORAS_CORR_TOTAL,COSTE_MTO_CORR_TOTAL,COSTE_MTO_CORR_MEDIO_POR_ORDEN,ID_Orden,Fecha,Tipo_Mantenimiento,Costo_Mantenimiento,Duracion_Horas,Ubicacion
0,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,15.40,154,52848.73,5284.873,929,2020-02-08 16:00:00,Correctivo,3143.58,8,Planta Este
1,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,15.40,154,52848.73,5284.873,1071,2020-02-14 14:00:00,Correctivo,2662.10,38,Planta Este
2,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,15.40,154,52848.73,5284.873,1519,2020-03-04 06:00:00,Correctivo,6329.16,3,Planta Sur
3,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,15.40,154,52848.73,5284.873,2093,2020-03-28 04:00:00,Preventivo,2645.45,28,Planta Este
4,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,15.40,154,52848.73,5284.873,2487,2020-04-13 14:00:00,Correctivo,6140.86,7,Planta Sur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9945,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,33.25,133,20625.56,5156.390,7594,2020-11-12 09:00:00,Preventivo,5636.49,32,Planta Oeste
9946,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,33.25,133,20625.56,5156.390,7769,2020-11-19 16:00:00,Preventivo,6220.96,42,Planta Norte
9947,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,33.25,133,20625.56,5156.390,8004,2020-11-29 11:00:00,Preventivo,7804.82,9,Planta Sur
9948,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,33.25,133,20625.56,5156.390,8845,2021-01-03 12:00:00,Correctivo,4160.08,38,Planta Este
9949,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,33.25,133,20625.56,5156.390,9332,2021-01-23 19:00:00,Preventivo,7158.61,40,Planta Oeste

In [ ]:
tabla_modelo.drop(columns="Fecha",inplace=True)

KeyError: "['Fecha'] not found in axis"

In [18]:
tabla_modelo

,ID_Equipo,Tipo_Equipo,Fabricante,Modelo,Potencia_kW,Horas_Recomendadas_Revision,DIAS_ENTRE_FALL_CONSEC,DIAS_ENTRE_FALL_CONSEC,MEDIA_TEMP,MEDIA_VIBR,...,Ordenes_Correctivo,DURACION_HORAS_CORR_MEDIO_POR_ORDEN,DURACION_HORAS_CORR_TOTAL,COSTE_MTO_CORR_TOTAL,COSTE_MTO_CORR_MEDIO_POR_ORDEN,ID_Orden,Tipo_Mantenimiento,Costo_Mantenimiento,Duracion_Horas,Ubicacion
0,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,10,15.40,154,52848.73,5284.873,929,Correctivo,3143.58,8,Planta Este
1,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,10,15.40,154,52848.73,5284.873,1071,Correctivo,2662.10,38,Planta Este
2,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,10,15.40,154,52848.73,5284.873,1519,Correctivo,6329.16,3,Planta Sur
3,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,10,15.40,154,52848.73,5284.873,2093,Preventivo,2645.45,28,Planta Este
4,1,Motor,Schneider,X100,1009,9656,39.111111,39.111111,106.908125,2.34625,...,10,15.40,154,52848.73,5284.873,2487,Correctivo,6140.86,7,Planta Sur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9945,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,4,33.25,133,20625.56,5156.390,7594,Preventivo,5636.49,32,Planta Oeste
9946,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,4,33.25,133,20625.56,5156.390,7769,Preventivo,6220.96,42,Planta Norte
9947,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,4,33.25,133,20625.56,5156.390,8004,Preventivo,7804.82,9,Planta Sur
9948,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,4,33.25,133,20625.56,5156.390,8845,Correctivo,4160.08,38,Planta Este
9949,499,Motor,ABB,M400,877,6907,88.333333,88.333333,95.410000,2.76100,...,4,33.25,133,20625.56,5156.390,9332,Preventivo,7158.61,40,Planta Oeste

In [19]:
from ydata_profiling import ProfileReport
profile = ProfileReport(tabla_modelo, title="Caso3 Profiling Report",
                        correlations={
                            "pearson": {"calculate": True},
                            "cramers": {"calculate": True},
                        })